apiVersion: apps/v1
kind : Deployment
metadata:
  name: test-api
spec:
  selector:
    matchLabels:
      app: test-api
  replicas: 2
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - name: test-api
          image: test-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8990


