apiVersion: apps/v1
kind : Deployment
metadata:
  name: api-k8
spec:
  selector:
    matchLabels:
      app: api-k8
  replicas: 2
  template:
    metadata:
      labels:
        app: api-k8
    spec:
      containers:
        - name: api-k8
          image: test-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8990


